### ISSUE TITLE
Imagemagick feed needs to be updated and is unstable

### ISSUE THREAD

**Issue by pmiess** [0install/apps#307]
The current image magic feeds archive files were deleted from https://imagemagick.org/download/binaries/ on 6/7/2020 and so there is no available implementation.

imagemagick.org deletes previous versions immediately and often updates every couple days or so.

http://ftp.icm.edu.pl/packages/ImageMagick/binaries/ keeps previous versions and would probably be a better source for this feed.

Reverting https://github.com/0install/apps/commit/0654dc79a699a9b08eba2f778ff186afbb47a9cf#diff-44b7300d71743f4d2cdb2ee92eb0ef2f6d11ce10a819fc4aa6e252e072a0ebd9 would fix this problem

**Comment by bastianeicher** [comment]
Thanks for reporting the broken feed.

I've fixed the issue by manually updating the feed to version 7.0.11-0 for now. I decided against reverting the commit because I prefer feeds pointing to projects' "own" domains for archive downloads when possible.

I still need to set up a new watch script and figure out how to handle old versions being deleted from `imagemagick.org`, however the frequency of new releases and therefore the size of the feed was getting a bit out of hand with the previous solution.
